### ISSUE TITLE
Output as 'hsv(...)'

### ISSUE THREAD

**Issue by urugator** [One-com/one-color#30]
Feature list in documentation states:
"Outputs as hex, rgb(...), rgba(...) or hsv(...)"

How do I output as hsv(...) ?

**Comment by papandreou** [comment]
Hmm, it appears that you don't :(

There's only `color.hex()`, `color.css()` and `color.cssa()`, and they all use the RGB colorspace.

I removed the `hsv(...)` part from the README in 9cb5e7f. I guess that just leaves whatever you were trying to do in the first place? :) Since neither [the css3 color spec](https://www.w3.org/TR/css3-color/) nor [the draft for the css4 color spec](https://drafts.csswg.org/css-color-4/) don't mention `hsv(...)` as a valid syntax, perhaps you were looking for `hsl(...)` or `hsla(...)`? We can't do right now, either, but it shouldn't be that hard to implement. The hardest part would probably be coming up with a name for the method, since  `hsl` is already used for an explicit conversion that outputs a `color.HSL` instance.

**Comment by papandreou** [comment]
Please reopen if you actually need this, or `hsla`|`hsl`.
