### ISSUE TITLE
Remove publishConfig from package.json

### ISSUE THREAD

**Issue by jmezach** [One-com/one-color#38]
The package.json for this node module currently includes a publishConfig section indicating that the package should be published to the public NPM registry. This makes it somewhat difficult to push this package to another feed.

I believe that if the publishConfig section isn't present npm will automatically push it to the public registry, unless otherwise specified, so removing it shouldn't hurt anyone.

Would it be possible to remove the publishConfig section from the package.json?

**Comment by papandreou** [comment]
Sure thing, fixed in https://github.com/One-com/one-color/commit/4137dc6cfc3d4f61f0fe1387f9d5857c9ed66282

I don't remember why that was put there to begin with. It's probably because we used to run a private repository, and it maybe helped us avoid accidentally publishing to that :)

Do you need a new release?

**Comment by jmezach** [comment]
No, not necessarily. I've hacked it for now by extracting the package,
removing the publishConfig and then repacking it. It's just nice to now we
won't have to do that again when a new version comes along ;).

Thanks for this. This issue can be closed :)

**Comment by papandreou** [comment]
Awesome, thanks for reporting it :)
